### ISSUE TITLE
Error adding deductions with one decimal place, e.g. HC3 with amount "5.4"

### ISSUE THREAD

**Issue by stevenalexander** [ministryofjustice/apvs-internal-web#213]
Error adding deductions with one decimal place (e.g. HC3 with amount "5.4"):

Environment: local

Steps:
1. View claim for a pending/new claim
2. Add a deduction with cost "5.4"

```
Unhandled rejection TypeError: Cannot read property 'forEach' of undefined
    at module.exports (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/app/routes/helpers/merge-claim-expenses-with-submitted-responses.js:8:19)
    at /Users/stevena/Source/moj-noms-apvs/apvs-internal-web/app/routes/claim/view-claim.js:76:36
    at tryCatcher (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/stevena/Source/moj-noms-apvs/apvs-internal-web/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by hvekriya** [comment]
Closed by #214
